"""
Exercise 2.4.9

Discovering Computer Science, Second Edition
Jessen Havill
"""

import turtle

truck = turtle.Turtle()
truck.speed(5)
truck.hideturtle()

truck.fillcolor('red')
truck.begin_fill()
truck.forward(300)
truck.left(90)
truck.forward(75)
truck.left(45)
truck.forward(25)
truck.left(45)
truck.forward(100)
truck.right(45)
truck.forward(100)
truck.left(45)
truck.forward(75)
truck.left(90)
truck.forward(70.71)
truck.right(90)
truck.forward(200)
truck.left(90)
truck.forward(92.677)
truck.left(90)
truck.forward(167.677)
truck.end_fill()

truck.up()
truck.forward(220)
truck.right(90)
truck.forward(50)
truck.left(90)
truck.down()

truck.fillcolor('black')
truck.begin_fill()
truck.circle(50)
truck.end_fill()
truck.up()
truck.right(90)
truck.backward(25)
truck.left(90)
truck.down()
truck.fillcolor('lightgray')
truck.begin_fill()
truck.circle(25)
truck.end_fill()

truck.up()
truck.right(90)
truck.forward(25)
truck.left(90)
truck.backward(300)
truck.down()
truck.fillcolor('black')
truck.begin_fill()
truck.circle(50)
truck.end_fill()

truck.up()
truck.right(90)
truck.backward(25)
truck.left(90)
truck.down()
truck.fillcolor('lightgray')
truck.begin_fill()
truck.circle(25)
truck.end_fill()
